{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let content=$class_attribute.content
     class_list=$content.class_constraint_list
     class_create_list=$content.class_create_constraint_list
     object_class=$content.object_class
     default_placement=$content.default_placement
     default_selection=$content.default_selection
     selection_type=$content.selection_type
     depth=$content.depth
     allow_edit=$content.allow_edit
     type=$content.type
     all_class_list=fetch(class,list)}
     	<div class="block">
		<fieldset>
		<legend>{'Type of object relations'|i18n( 'design/standard/class/datatype' )}</legend>
		
			<div class="element">	    
				<select name="ContentClass_ezobjectrelationbrowse_type_{$class_attribute.id}">
				    <option value="0" {section show=eq($type, 0)}selected="selected"{/section}>{"New and existing objects"|i18n("design/standard/class/datatype")}</option>
				    <option value="1" {section show=eq($type, 1)}selected="selected"{/section}>{"Only new objects"|i18n("design/standard/class/datatype")}</option>
				    <option value="2" {section show=eq($type, 2)}selected="selected"{/section}>{"Only existing objects"|i18n("design/standard/class/datatype")}</option>
				</select>		
			</div>
		</fieldset>
	</div>
	
	<br/>
	<br/>
	
	<div class="block">
		<fieldset>
		<legend>{'Existing Objects'|i18n( 'design/standard/class/datatype' )}</legend>

		<div class="block">
			<fieldset>
			<legend>{'Type of listing'|i18n( 'design/standard/class/datatype' )}</legend>
				<div class="element">
					<label>{'Selection method'|i18n( 'design/standard/class/datatype' )}</label><div class="labelbreak"></div>
					<select name="ContentClass_ezobjectrelationbrowse_selection_type_{$class_attribute.id}">
					    <option value="0" {eq( $selection_type, 0 )|choose( '', 'selected="selected"' )}>{'Default Browse'|i18n( 'design/standard/class/datatype' )}</option>
					    <option value="1" {eq( $selection_type, 1 )|choose( '', 'selected="selected"' )}>{'AJAX'|i18n( 'design/standard/class/datatype' )}</option>
					    <option value="3" {eq( $selection_type, 3 )|choose( '', 'selected="selected"' )}>{'Drop-down'|i18n( 'design/standard/class/datatype' )}</option>
					    <option value="2" {eq( $selection_type, 2 )|choose( '', 'selected="selected"' )}>{'Multiple selection list'|i18n( 'design/standard/class/datatype' )}</option>
					    <option value="4" {eq( $selection_type, 4 )|choose( '', 'selected="selected"' )}>{'List with checkboxes'|i18n( 'design/standard/class/datatype' )}</option>
					    <option value="5" {eq( $selection_type, 5 )|choose( '', 'selected="selected"' )}>{'List with radio buttons'|i18n( 'design/standard/class/datatype' )}</option>
					</select>
				</div>

				<div class="element"
					<label>{"Depth"|i18n("design/standard/class/datatype")}</label><div class="labelbreak"></div>
					<select name="ContentClass_ezobjectrelationbrowse_depth_{$class_attribute.id}">
					    <option value="1" {eq( $depth, 1 )|choose( '', 'selected="selected"' )}>{'List'|i18n( 'design/standard/class/datatype' )}</option>
					    <option value="0" {eq( $depth, 0 )|choose( '', 'selected="selected"' )}>{'Tree'|i18n( 'design/standard/class/datatype' )}</option>
					    <option value="2" {eq( $depth, 2 )|choose( '', 'selected="selected"' )}>{'Tree - 2 levels'|i18n( 'design/standard/class/datatype' )}</option>
					    <option value="3" {eq( $depth, 3 )|choose( '', 'selected="selected"' )}>{'Tree - 3 levels'|i18n( 'design/standard/class/datatype' )}</option>
					    <option value="4" {eq( $depth, 4 )|choose( '', 'selected="selected"' )}>{'Tree - 4 levels'|i18n( 'design/standard/class/datatype' )}</option>
					    <option value="5" {eq( $depth, 5 )|choose( '', 'selected="selected"' )}>{'Tree - 5 levels'|i18n( 'design/standard/class/datatype' )}</option>
					</select> 
				</div>   
			</fieldset>
		</div>  

		<br/>

		<div class="block">
			<div class="block">
				<fieldset>
				<legend>{'Default selection node'|i18n( 'design/standard/class/datatype' )}</legend>
				<div class="element">
					<p>{'Select the node from which the list will be created.'|i18n('design/standard/class/datatype')}</p>

						{section show=$default_selection}
						{let default_selection_node=fetch( content, node, hash( node_id, $default_selection.node_id ) )}
						<table class="list" cellspacing="0">
						<tr>
						    <th>{'Name'|i18n( 'design/standard/class/datatype' )}</th>
						    <th>{'Type'|i18n( 'design/standard/class/datatype' )}</th>
						    <th>{'Section'|i18n( 'design/standard/class/datatype' )}</th>
						</tr>
						<tr>
						    <td>{$default_selection_node.class_identifier|class_icon( small, $default_selection_node.class_name )}&nbsp;{$default_selection_node.name|wash}</td>
						    <td>{$default_selection_node.class_name|wash}</td>
						    <td>{let section_object=fetch( section, object, hash( section_id, $default_selection_node.object.section_id ) )}{section show=$section_object}{$section_object.name|wash}{section-else}<i>{'Unknown section'|i18n( 'design/standard/class/datatype' )}</i>{/section}{/let}</td>
						</tr>
						</table>
						{/let}

						<input type="hidden" name="ContentClass_ezobjectrelationbrowse_default_selection_{$class_attribute.id}" value="{$default_selection.node_id}" />
						{section-else}
						<p>{'No default selection node selected.'|i18n( 'design/standard/class/datatype' )}</p>
						<input type="hidden" name="ContentClass_ezobjectrelationbrowse_default_selection_{$class_attribute.id}" value="" />
						{/section}

						{section show=$default_selection}
						    <input class="button" type="submit" name="CustomActionButton[{$class_attribute.id}_disable_selection]" value="{'Remove location'|i18n('design/standard/class/datatype')}" />
						{section-else}
						    <input class="button-disabled" type="submit" name="CustomActionButton[{$class_attribute.id}_disable_selection]" value="{'Remove location'|i18n('design/standard/class/datatype')}" disabled="disabled" />
						{/section}

						<input class="button" type="submit" name="CustomActionButton[{$class_attribute.id}_browse_for_selection]" value="{'Select location'|i18n('design/standard/class/datatype')}" />
				</div>
				</fieldset>
			</div>				
		</div>

		<br/>

		<div class="block">
			<fieldset>
				<legend>{'Selectable content classes'|i18n( 'design/standard/class/datatype' )}</legend>
					<div class="element">	    
						<p>{'Select the type (class) of content objects the user may add as related items.'|i18n('design/standard/class/datatype')}</p>
						<select name="ContentClass_ezobjectrelationbrowse_class_list_{$class_attribute.id}[]" multiple="multiple" size="10">
						    <option value="" {section show=$class_list|lt(1)}selected="selected"{/section}>{'Any'|i18n('design/standard/class/datatype')}</option>
						{section name=Class loop=$all_class_list}
						    <option value="{$:item.identifier|wash}" {section show=$class_list|contains($:item.identifier)}selected="selected"{/section}>{$:item.name}</option>
						{/section}
						</select>		
					</div>
			</fieldset>
		</div>
		</fieldset>
	</div>

	<br/>
	<br/>
	
	<div class="block">
	<fieldset>
		<legend>{'New Objects'|i18n( 'design/standard/class/datatype' )}</legend>

		<div class="block">
			<fieldset>
			<legend>{'Createable content classes'|i18n( 'design/standard/class/datatype' )}</legend>
				<div class="element">	    
					<p>{'Select the type (class) of content objects the user may create as related items.'|i18n('design/standard/class/datatype')}</p>
					<select name="ContentClass_ezobjectrelationbrowse_class_create_list_{$class_attribute.id}[]" multiple="multiple" size="10">
					    <option value="" {section show=$class_create_list|lt(1)}selected="selected"{/section}>{'Any'|i18n('design/standard/class/datatype')}</option>
					{section name=Class loop=$all_class_list}
					    <option value="{$:item.identifier|wash}" {section show=$class_create_list|contains($:item.identifier)}selected="selected"{/section}>{$:item.name}</option>
					{/section}
					</select>		
				</div>
			</fieldset>
		</div>

		<br/>

		<div class="block">
			<div class="block">
			<fieldset>
			<legend>{'Default location for new objects'|i18n( 'design/standard/class/datatype' )}</legend>
			{section show=$default_placement}
			{let default_location=fetch( content, node, hash( node_id, $default_placement.node_id ) )}
			<table class="list" cellspacing="0">
			<tr>
			    <th>{'Name'|i18n( 'design/standard/class/datatype' )}</th>
			    <th>{'Type'|i18n( 'design/standard/class/datatype' )}</th>
			    <th>{'Section'|i18n( 'design/standard/class/datatype' )}</th>
			</tr>
			<tr>
			    <td>{$default_location.class_identifier|class_icon( small, $default_location.class_name )}&nbsp;{$default_location.name|wash}</td>
			    <td>{$default_location.class_name|wash}</td>
			    <td>{let section_object=fetch( section, object, hash( section_id, $default_location.object.section_id ) )}{section show=$section_object}{$section_object.name|wash}{section-else}<i>{'Unknown section'|i18n( 'design/standard/class/datatype' )}</i>{/section}{/let}</td>
			</tr>
			</table>
			{/let}

			<input type="hidden" name="ContentClass_ezobjectrelationbrowse_placement_{$class_attribute.id}" value="{$default_placement.node_id}" />
			{section-else}
			<p>{'New objects will not be placed in the content tree.'|i18n( 'design/standard/class/datatype' )}</p>
			<input type="hidden" name="ContentClass_ezobjectrelationbrowse_placement_{$class_attribute.id}" value="" />
			{/section}

			{section show=$default_placement}
			    <input class="button" type="submit" name="CustomActionButton[{$class_attribute.id}_disable_placement]" value="{'Remove location'|i18n('design/standard/class/datatype')}" />
			{section-else}
			    <input class="button-disabled" type="submit" name="CustomActionButton[{$class_attribute.id}_disable_placement]" value="{'Remove location'|i18n('design/standard/class/datatype')}" disabled="disabled" />
			{/section}

			<input class="button" type="submit" name="CustomActionButton[{$class_attribute.id}_browse_for_placement]" value="{'Select location'|i18n('design/standard/class/datatype')}" />

			</fieldset>

		</div>	
	</fieldset>
	</div>
	<br/>
	<div class="block">
		<fieldset>
		<legend>{'Allow inline edit'|i18n( 'design/standard/class/datatype' )}</legend>
			<div class="element">
				<p>{"Allow user to edit related objects inline (only available for list type 'default browse')."|i18n("design/standard/class/datatype")}</p>

				<input type="checkbox" name="ContentClass_ezobjectrelationbrowse_allow_edit_{$class_attribute.id}" {$allow_edit|choose("",'checked="checked"')} />
				<input type="hidden" name="ContentClass_ezobjectrelationbrowse_allow_edit_{$class_attribute.id}_exists" value="1" />
			</div>
		 </fieldset>
	</div>
{/let}
